[package]
name = "user_lib"
version = "0.1.0"
edition = "2021"
default-run = "initproc"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]



[[bin]]
name = "multithread"